# -*- coding: utf-8 -*-
# Part of Orbex. See LICENSE file for full copyright and licensing details.


{
    'name': 'Base',
    'version': '1.3',
    'category': 'Hidden',
    'description': """
The kernel of Orbex, needed for all installation.
===================================================
""",
    'data': [
        'data/res_bank.json',
        'data/res.lang.csv',
        'data/res_lang_data.json',
        'data/res_partner_data.json',
        'data/res_currency_data.json',
        'data/res_company_data.json',
        'data/res_users_data.json',
        'data/report_paperformat_data.json',
        'data/res_country_data.json',
        'data/ir_demo_data.json',
        'security/base_groups.json',
        'security/base_security.json',
        'wizard/wizard_ir_model_menu_create_views.json',
        'views/base_menus.json',
        'views/decimal_precision_views.json',
        'views/res_config_views.json',
        'data/res.country.state.csv',
        'views/ir_actions_views.json',
        'views/ir_asset_views.json',
        'views/ir_config_parameter_views.json',
        'views/ir_cron_views.json',
        'views/ir_cron_trigger_views.json',
        'views/ir_filters_views.json',
        'views/ir_mail_server_views.json',
        'views/ir_model_views.json',
        'views/ir_attachment_views.json',
        'views/ir_rule_views.json',
        'views/ir_sequence_views.json',
        'views/ir_ui_menu_views.json',
        'views/ir_ui_view_views.json',
        'views/ir_default_views.json',
        'data/ir_config_parameter_data.json',
        'data/ir_cron_data.json',
        'report/ir_model_report.json',
        'report/ir_model_templates.json',
        'views/ir_logging_views.json',
        'views/ir_qweb_widget_templates.json',
        'views/ir_module_views.json',
        'data/ir_module_category_data.json',
        'data/ir_module_module.json',
        'report/ir_module_reports.json',
        'report/ir_module_report_templates.json',
        'wizard/base_module_update_views.json',
        'wizard/base_language_install_views.json',
        'wizard/base_import_language_views.json',
        'wizard/base_module_upgrade_views.json',
        'wizard/base_module_uninstall_views.json',
        'wizard/base_export_language_views.json',
        'wizard/base_partner_merge_views.json',
        'data/ir_demo_failure_data.json',
        'views/ir_profile_views.json',
        'views/res_company_views.json',
        'views/res_lang_views.json',
        'views/res_partner_views.json',
        'views/res_bank_views.json',
        'views/res_country_views.json',
        'views/res_currency_views.json',
        'views/res_groups_views.json',
        'views/res_users_views.json',
        'views/res_users_apikeys_views.json',
        'views/res_device_views.json',
        'views/res_users_identitycheck_views.json',
        'views/res_config_settings_views.json',
        'views/report_paperformat_views.json',
        'security/ir.model.access.csv',
    ],
    'demo': [
        'data/res_users_demo.json',
        'data/res_partner_bank_demo.json',
        'data/res_currency_demo.json',
        'data/res_currency_rate_demo.json',
        'data/res_bank_demo.json',
        'data/res_partner_demo.json',
        'data/res_partner_image_demo.json',
    ],
    'assets': {
        'web.assets_tests': [
            'base/static/tests/**/*',
        ],
    },
    'installable': True,
    'auto_install': True,
    'post_init_hook': 'post_init',
    'license': 'OSPL-1',
}
